version: '3'

services:
  app_db_dev:
    container_name: "app_db_dev"
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: elder123
      POSTGRES_PASSWORD: elder123
      PGTZ: America/Caracas
      TZ: America/Caracas
      # POSTGRES_DB: results_v2
    volumes:
      - app_db_dev_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/01_file.sh
      - ./bk.sql:/docker-entrypoint-initdb.d/02_file.sql
    ports:
      - "5444:5432"
  app_dev:
    image: "app_resultados"
    container_name: "app_dev"
    environment:
      TZ: America/Caracas
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
    build:
      context: .
      dockerfile: app-dev-dockerfile
      args:
        ARCH: $ARCH
    volumes:
      - ./app/logs:/app/src/logs
    depends_on:
      - app_db_dev
    ports:
      - "8888:80"
      - "4444:443"
volumes:
  app_db_dev_data:


